-- MySQL Script generated by MySQL Workbench
-- Sun 16 Aug 2015 04:23:23 PM CEST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema asciidoc_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asciidoc_service` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `asciidoc_service` ;

-- -----------------------------------------------------
-- Table `asciidoc_service`.`apikeys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asciidoc_service`.`apikeys` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `apikey` VARCHAR(40) NOT NULL,
  `owner` VARCHAR(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQUE1` (`apikey` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asciidoc_service`.`asciidocs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asciidoc_service`.`asciidocs` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(100) NOT NULL,
  `filename` VARCHAR(100) NOT NULL,
  `path` VARCHAR(255) NOT NULL,
  `sha` VARCHAR(40) NOT NULL,
  `created` DATETIME NOT NULL,
  `url` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `title`),
  UNIQUE INDEX `UNIQUE2` (`path` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asciidoc_service`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asciidoc_service`.`categories` (
  `asciidocId` INT UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`asciidocId`),
  CONSTRAINT `fk_categories_asciidocs1`
    FOREIGN KEY (`asciidocId`)
    REFERENCES `asciidoc_service`.`asciidocs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asciidoc_service`.`contents`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asciidoc_service`.`contents` (
  `asciidocId` INT UNSIGNED NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `doc` MEDIUMTEXT NOT NULL,
  PRIMARY KEY (`asciidocId`, `type`),
  CONSTRAINT `fk_translation_asciidocs1`
    FOREIGN KEY (`asciidocId`)
    REFERENCES `asciidoc_service`.`asciidocs` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
