-- MySQL Script generated by MySQL Workbench
-- Thu 02 Apr 2015 01:55:30 PM CEST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema asciidoc_service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `asciidoc_service` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `asciidoc_service` ;

-- -----------------------------------------------------
-- Table `asciidoc_service`.`apikeys`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asciidoc_service`.`apikeys` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `apikey` VARCHAR(40) NOT NULL,
  `owner` VARCHAR(100) NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UNIQUE1` (`apikey` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asciidoc_service`.`asciidoc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asciidoc_service`.`asciidoc` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `apikeys_id` INT UNSIGNED NOT NULL,
  `doc` MEDIUMTEXT NOT NULL DEFAULT '',
  PRIMARY KEY (`id`),
  INDEX `fk_asciidoc_apikeys_idx` (`apikeys_id` ASC),
  CONSTRAINT `fk_asciidoc_apikeys`
    FOREIGN KEY (`apikeys_id`)
    REFERENCES `asciidoc_service`.`apikeys` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `asciidoc_service`.`translation`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `asciidoc_service`.`translation` (
  `type` VARCHAR(20) NOT NULL,
  `asciidoc_id` INT UNSIGNED NOT NULL,
  `doc` MEDIUMTEXT NOT NULL DEFAULT '',
  PRIMARY KEY (`type`, `asciidoc_id`),
  INDEX `fk_translation_asciidoc1_idx` (`asciidoc_id` ASC),
  CONSTRAINT `fk_translation_asciidoc1`
    FOREIGN KEY (`asciidoc_id`)
    REFERENCES `asciidoc_service`.`asciidoc` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
